language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
- if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn sonar:sonar; fi
- npm test
- npm run build
deploy:
  provider: surge
  cleanup: true
  domain: sytw.surge.sh
  project: "./build/"
on:
  branch: master
notifications:
  slack:
    secure: iKpIDRL46XWkUPRQ8uGELUjW5OS133wZ54f3J/pOSPAL/1y8fsk4zhCEaNEdn53L6gIuLBxzsxG+ySLe1O8aZzDkFhqzluEKiIQuRiyY/C7jVYehRpBy8RDf8xgMaf5PA8bGBdxtYYmofobL2lMU6IrQT17xwsRCBGlIJmvQ7vOykPxmcdByOHR2enDJjkeUbe1Np+L+BUOeYSI602ie3h8SCLAnmM0iN7U6tnFsT6JTLYWjGR8sYN27+trq0VAhDeVui/ruX113o8+7mxwTbnZlQGdAjN709Ydpo2+AGolRpM9C/YpHrUOMOAfZyd64cqjuMEiD6I/WkUR9jn8j93FPax5vTYH44GYifWbfSKagwYcK6tPOzrrWq1hXoNj/JRL2ejdhkEhLfZx2RDS82/r8KD0vPR47MiKtdoAFvCPhBFxtE0DdQV/ZBA9Ak88ZP2LpAHcBsTHKDCA806TKnjzP+VHLNHVgGuELabT/HLu0peMk0PAY9FPzlZmkL/kWEb/Q6juq5HWmtFggs3bArc+AEDcZbXOvQ14G9MRkRVrXU0wNd1DhWSsaOjKTs+taHQUvoN+usxdGpD8uuNp4kAUQA8FwPDD4jyFGr053c2VbMywDhr8ZPKl5SCHcQ5LxflGoqxd4W56bXn0zNKv9oJTG5oqoV0irWqRVXWH6KWA=
addons:
  sonarcloud:
    organization: "sytw2019" # the key of the org you chose at step #3
    token:
      secure: "owJpGuoFLA3icmx8JDsgmz1ynpmVKbgECs5LFfq5fEWee65V0uLNBJNikBm9hlEUUfS+cgS5LGQ3gwCwzq9JNampDPkP/ZfASyq9UqeAVAqj8Ei6vY0e4x6ZGn7drp5F5hvQ33Qz81juW6z9ianSy7T6yzkTXwHZQ1YA3qW3vK6HKBdc46D288mmSG4Jo1TIzwbp6KkDXzxcUjjgO8eskhuAZFgcYq3Ujpdu2AVIoF4RH6p7lKoDHshJT/qfsNzHnauWabxlQEDnE9avdnGSh1g4Dsxm4HmE9KPDbk4EVde3dPgWOGNbLvX1WEh7dZA5WU4xAYp3yXE+7WZegPINaZuPWAzvvY77/JaY/NQBoEItwLRD1qSmo1cyK/3fMfMhano+9UySLh69PVQpRHxwjioECLaaS4Q5Y97LlF7QzlpiFyOwHpowxtlSHskoV9UZ5w5SJ8UO+WsYnHqhtgNBrtIyb0Wyxl2GUoQaYnb60D8qu9RYeZDRjmVkYpjKfzofDmJdOv4sCO3DKRXMRrhny4GHNaCZCLiy+MCg6HjrceHRGxPpjYnFtyX+MLsHz2rcartH9ZC9cl9KStBuKF1/AowViWKmRUZA+KlviCNIO6R304wv3OpuL6f4fN5EmtBvlSAR6pk4FbrD+YqHMcoxLWE68j9Q6/2RQJvli3C4zNM=" # encrypted value of your token
