language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sytw.surge.sh
  project: "./build/"
true:
  branch: master
notifications:
  slack:
    secure: Mq3oBaZQxIoSBkmnX2jbFiT+QVoJeuBhXG1FMUDkh2qgB1r3VMfCUWWA9oY6FHFUD4qrimCNO3R0KyjBlWv3A/ZKXUCn0N5UfZM2GYbNs2etBo++jd5U4Bo4ejBevsrHmC2MzUx/FrTmvDXS5r9ADfkJGKfFdAeCNwyQs5Ah2w0xYrN+Noy5QFsQFcuTWuzUZKwMW8jz4Lz1s8jriC9djqkJmp4AogON3ATxbV+qSM1cPAfqu6ZnujXc1atyL3qnx0/fYTmpk/tOMaxw92p92FOdXVjzlSA7v9CjU1nel17+vYwpakDMeiADC1sGEpERUvLY3FG0LwBJqgWM1wmgxC4o6wxraeztSUlxiSLa70AObWLGD39JEZRygrc2lw4Obp/wr2wCrfVZj6v0ormK2ry/AlcSxM2TSdLauseU3+YTu7bTBXQ56eJuQffWlfcPhHFIbKfXJmwBwG9VkbelUqmyvk00B+R2+OTAHG1a+tlNTWmSIl3HV3M+zisObKDcduFcxzBJM3FSIRWHiQa75Jd1dqykKO7Y3W52/ArUmY+wQxR8VxKpGZ8Baa9o+SW/HkejI1VECzlLK2QSbsmWqAuROAK01p4IPRZPoEQnjdbwiqsyD5Hpv9XkGsjGE2YiH+ddYN5JGFZQ3/ODW8hafpow/JI+IEwRlDaIpeTd3G4=
