language: node_js
node_js:
  - stable
before_install:
  - cd frontend
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: sytw2019
    token:
      secure: lwEQbrznwAjCqmh/kIgcintJIJXRzmLPiAMX746wSrDQxL4tbFfAGMFNNy+VNi8HkZdgy7+1zGhe1bq1honvejqPHnnwc6fVJlRjR4EF+UTwPLzg4LjjUHySmbb+RvHuJLCzW97hsl8ZL9Izvquydlae04gFxJgZdYK01h/YGvIouRsbQR9NtquGrZeROLc86unDuv7zGFbbpIyQfpir3ddVg2H0pwLCojBprsNTw6xMWI5tPHju51fELzoR3ALeos+pFuaqcXYu3qEcrpDGw1GH7QJbMLc5Ywb2NAKmEgt9GYKDbWobPU8Db4gfwso4RuuX1Q1ccEiwX9yRinD21dvRN9IQETCWUARpK7uq0bvIRsZ5jlIr4s2+Z1UeHxAKr/dFFIQ2WRHHoMTFV8vG60EFjX3D2t9NiPOSQ2rdNvxMFVy8cRaMbLreKlD+PcOFPyEcp/pFokbABgixMTgXUm9aTfK0FBxcd8dvNg+hrj+MMlpd+56wmNTKya/bmmoybZkraVVewysXACPnULYozeIXEdNRaQ48F5Bo+CVa4crJESj9/Gb/KjW3XPBAPs6emN2Q6rHAdYXSUFuKJoDM0dLkwWl86yPIvx8JUEFB1DiJTV95bx9dtPE4AEf8H7q3yK69tIpLDG5VMAYn/7QaaJF2b6Ip36zhwso0sZjzALM=
script:
  - sonar-scanner
  - npm test
  - codecov
  - npm run build
deploy:
  - provider: surge
    skip_cleanup: true
    project: './frontend/dist'
    domain: eventfinder.surge.sh
    on:
      branch: master
  - provider: surge
    skip_cleanup: true
    project: './frontend/dist'
    domain: staggingfinder.surge.sh
    on:
      branch: dev
  - provider: heroku
    api_key:
      secure: j6aLxX8bgiZA/LhOCfCbPPqITygcDOJ/UgkDprHJ/0j2DLe7WuKONQhvudXnvbRD2gscVm7+GwtERb5H2i0hTNGWot/wDf1ubp/H1sGPvdQX6Ey7l26/FPnB+c4cZNohvQ3UbqsXEZb8w3uK3Fh/JPq6bL9CpIpJX1duAm22PvHnNWOloIiLA1ND255y9p9yqtG/DnM3OAITgFcVpuq3xpOSUhsI+B2QxjBoDav4Yr9GV7P3ew0qlEpL5zAEBCPAJDQht+WpRlZ6zzGr8BrtBh5rsvXy5R9BzTtIRIsoAIFASqMV1/5ae7Xtw3N4DCGKkLt1TckuwqpWMe0mY0CEEqBLt4N8MiyilZvNMTbYfX1TXUb0nAW0ZqkjaFJ61slxQXpVOWzSk00Ex2M82w3jD7wGW2gi4x/N1n2hgAo/lMJFnvEPfxisEba5VFgOOb4zfolqUoMxo+GCY7tJA2FUA8e/8x+vlQgjGon24Ma6ACDg35wHnY6M2VybBjjaEehu73nhogGQ47ExRCl00zrXdILb4MMXSPMV/z+ie4gz7LyaQqVB+PBKcuugMscV0HO+x6RpW3K+FeG+MpJBCac6q7a82zkjbyIgGWboyNqNm6PuX4iqfc/KaGFW+AjST/XcYGFiC4prmhvnWaPOPalH1ESDCFA1RsD87Z/CdnwLcuk=
    app: eventfinder-sytw
notifications:
  slack:
    secure: iKpIDRL46XWkUPRQ8uGELUjW5OS133wZ54f3J/pOSPAL/1y8fsk4zhCEaNEdn53L6gIuLBxzsxG+ySLe1O8aZzDkFhqzluEKiIQuRiyY/C7jVYehRpBy8RDf8xgMaf5PA8bGBdxtYYmofobL2lMU6IrQT17xwsRCBGlIJmvQ7vOykPxmcdByOHR2enDJjkeUbe1Np+L+BUOeYSI602ie3h8SCLAnmM0iN7U6tnFsT6JTLYWjGR8sYN27+trq0VAhDeVui/ruX113o8+7mxwTbnZlQGdAjN709Ydpo2+AGolRpM9C/YpHrUOMOAfZyd64cqjuMEiD6I/WkUR9jn8j93FPax5vTYH44GYifWbfSKagwYcK6tPOzrrWq1hXoNj/JRL2ejdhkEhLfZx2RDS82/r8KD0vPR47MiKtdoAFvCPhBFxtE0DdQV/ZBA9Ak88ZP2LpAHcBsTHKDCA806TKnjzP+VHLNHVgGuELabT/HLu0peMk0PAY9FPzlZmkL/kWEb/Q6juq5HWmtFggs3bArc+AEDcZbXOvQ14G9MRkRVrXU0wNd1DhWSsaOjKTs+taHQUvoN+usxdGpD8uuNp4kAUQA8FwPDD4jyFGr053c2VbMywDhr8ZPKl5SCHcQ5LxflGoqxd4W56bXn0zNKv9oJTG5oqoV0irWqRVXWH6KWA=
