language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sytw.surge.sh
  project: "./build/"
true:
  branch: master
notifications:
  slack:
    rooms:
      secure: G3xlVYRDMkxc5zdo9R4RTVUJyirGuJey0UClMi7Kh0qNv9ZKpKmdNJK2/9fOQbQhU5Gbd+MxHrOTpVeozDh+zT1BoDi/17OwKRPGfKAfAXox09hcTFci4ZDy2h3y+q5T8GMsThKB1VM1TGsVykbrYyVqtZX3SYCMQVxYB8ST0HhAg7Iy8MqEAjKWs4f9hFVI82/ff5ddZBFCNUrkJFn4ELgoxxoKiDZ/Ik6KmENFPhnjIvxwPN6t/bqgNL9fKqC2ugoH87ezslu8I1XfLQ7nIHoUOOjoDEvoKjUdrqmgqaoDVAzviYF4U+CFom0tucOi8xdQNg6Oariw1VX3aqc+55qBxWDXr7YEpRMyKYWcd06ABaq2KYxaI1ACaijOkQL5JDu+t37IPYtOiOd//fvr/xSZF18+Kg/8NZwqIhe6lRsEC5eSSGQi4hCmH7u9LCjom2CEhhaF1QrTTWh/M+fH8NUat5I50AFtaOT4QnxBbBSuabVkW5Z4K75aJhzfjXa8atrnW9lGhX8Fwd1KNfKH9OhY/hjgpM/qOUPEousVSNTc7gTld7CTanGpab0TFnMYvRb/Fr8vjqHCeY+USKObva/ha1wps3l66oB1snO77iCMN1S3TBPpIEWlVqGSJM6CVKT9BZ7x6EjegEzGYSZRQvT/eQJr7SM+kcVWg3MJIr4=
      on_success: always
      on_failure: always
