language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sytw.surge.sh
  project: "./build/"
true:
  branch: master
notifications:
  slack:
    secure: S6wDaJkxjzFpptHq45ZyS4EqCewQ+ez9QFcOew4s2mHpi+mkB8Adem/7cnHnilB12xNekn0SK4qFYoiMxRCCPKDrx7dXd1cvKqBjhyd+oRWHqO/FlLCNj2YtaVHWDEaNW5uM1UgbT4oakqxRSynGrRVFzDOeriq9b77+rZvRkkYggnYtvY6LW+ntdaF/z5J71+CB4twO3v3e0QpKp2oPpX526Q49IFW9S8Q2UDlhb9RC1ajplA+47vpHtpxIlfUU4ccSmeldC5mYWyzv9U85MMzuyTdkZz2HrJdUMwHo8ozCNBNv+bwhnyEI/HPAuAIf2/+aZX+2BLE1NhCKhAkPSlpUug39pMq0FxVgZRHh+WzVW9TpaLxUFrJk042j4hd44QCd7wioFp4cKpvK6OvdOjkNIJZZA/wmmTlVQD06wtLffTa5Y76QoMcg+JCLltFI28CXn2vVPSERKbhT9cwiNgLcdA0o83LNw5B2H9pkJb3OKb3KsTvpetYThgG26RrMLUJeFs1cZLVSELw/Em4Y92/bB+aG+lVPT0tTcB2wHXRDmzkRm2dZzVam85DXDaqpNo3dcwxLt8uvGumd1kr0vWwZD+h8EBu+8AWFgBLcT39No6Cx5gwuwRzO3lVasEUf69bpH+AY5ofYb/ZdV5elsDpwrbt7+5WdVJDBGPgSLEE=
