language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: sytw.surge.sh
  project: "./build/"
true:
  branch: master
notifications:
  slack:
    rooms:
      secure: G0VwHW05+jLaelGFM/XeS1T6mkTVLcScCp+8/5TlawSaCjPsKiF0AYlUIpKjwb8w4JImA5U1ktQEWgKMwXQapFRO6GodEyWFAf/9R56bNC2JF52KxOUadONqofkVaiewXokucUUtQ0CstN+YvPL5/ajDpXTkVstcd762cB3rGA3ZYC9BAJ31Diq4cytjxXi9wekXGub4obKWKBQFnY6uWYDqGOG7+0+2ufza1NAFtOEGmyM+xCj1vbpyzEf9cVYVehsxJtGrQ8mVHnf/BzykL2aul7dSsaFKtVOAS0ZhN7JGs229/Q/aRJE8BoKgk3VOMygywk1M6OZvVYu3BAHHnPvFDaZGkAJUHq5cyi/zOxUBl3jQ23akLAeJTikIxv9mWt2PLsAUHmUeK2ttnlzxPHDhpRqiOz5D6GSDlv7hHxoSbSUE6HKYccIDBCbhs1MpelaDOK9/CgCarCksYnFKUyDxCGI5Dz0EBtdMrj8mfx6qGKlH+VyQPo2XXDW344vWz3KmpLbtk1Eptm5ke6KB3EB6ldvhly80LnRLiFPfWyokQNtvucpPi8sKYezj4+NFxwTiEfOuRXO+pUYUg9yv8Tr5wjuqH8owAiwTtc0RCzTkMuP0oUY+NP8oXQFCsvbGgADr2hq0jSmQzaTUFFz+SQMPBtctLOgeiMJkX4L7LeY=
    on_success: always
    on_failure: always